before_script:linux:
    script: rm -rf *
    tags:
    - linux
    - git

stages:
- test
- build

test:linux:
    stage: test
    script: make && make clean
    dependencies:
    - before_script:linux

build:linux:
    stage: build
    script: make
    dependencies:
    - test:linux
    artifacts:
        paths:
        - git-hash
        expire_in: 1 month