stages:
- clean
- test
- build

before_script:linux:
    stage: clean
    script: rm -rf *
    tags:
    - linux
    - git

test:linux:
    stage: test
    script: make && make clean
    dependencies:
    - clean:linux
    tags:
    - linux
    - git

build:linux:
    stage: build
    script: make
    dependencies:
    - test:linux
    tags:
    - linux
    - git
    artifacts:
        paths:
        - git-hash
        expire_in: 1 month
